services:
  postgres_engine:
    ports:
      - "5432:5432"
    image: postgres:16-alpine
    networks:
      - hack-net
    environment:
      POSTGRES_USER: ${ENGINE_PG_USER}
      POSTGRES_PASSWORD: ${ENGINE_PG_PASSWORD}
      POSTGRES_DB: ${ENGINE_PG_DATABASE}
    volumes:
      - "engine_pgdata:/var/lib/postgresql/data"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${ENGINE_PG_USER} -d ${ENGINE_PG_DATABASE}" ]
      interval: 5s
      timeout: 5s
      retries: 5

  migrations:
    image: migrate/migrate
    networks:
      - hack-net
    volumes:
      - ${PWD}/services/engine-go/migrations:/migrations
    command:
      - -path=/migrations/
      - -database=postgres://${ENGINE_PG_USER}:${ENGINE_PG_PASSWORD}@postgres_engine:5432/${ENGINE_PG_DATABASE}?sslmode=disable
      - up
    depends_on:
      postgres_engine:
        condition: service_healthy

  # --- НОВЫЙ БЛОК: Python Analytics Service ---
  analytics-report:
    build:
      context: ./services/analytics-python
      dockerfile: Dockerfile
    networks:
      - hack-net
    depends_on:
      postgres_engine:
        condition: service_healthy
    environment:
      - ENGINE_PG_USER=${ENGINE_PG_USER}
      - ENGINE_PG_DATABASE=${ENGINE_PG_DATABASE}
      - ENGINE_PG_PASSWORD=${ENGINE_PG_PASSWORD}
      - ENGINE_PG_HOST=postgres_engine
      - CERTS_PATH=/etc/certs
      - PYTHONUNBUFFERED=1
    ports:
      - "50051:50051"
    volumes:
      # Пробрасываем сертификаты так же, как в Go-сервисе
      - ./certs/ca.crt:/etc/certs/ca.crt:ro
      - ./certs/server.crt:/etc/certs/server.crt:ro
      - ./certs/server.key:/etc/certs/server.key:ro

  test-engine:
    build:
      context: .
      dockerfile: services/engine-go/Dockerfile
    networks:
      - hack-net
    depends_on:
      postgres_engine:
        condition: service_healthy
      analytics-report: # Добавляем зависимость, если Go сервис вызывает Python
        condition: service_started
    environment:
      APP_ENV: development
      ANALYTICS_ADDR: analytics-report:50051 # Чтобы Go знал, куда стучаться
    env_file: services/engine-go/.env
    ports:
      - "50036:50036"
    volumes:
      - ./certs/ca.crt:/etc/certs/ca.crt:ro
      - ./certs/server.crt:/etc/certs/server.crt:ro
      - ./certs/server.key:/etc/certs/server.key:ro

networks:
  hack-net:
    driver: bridge
volumes:
  engine_pgdata: