# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: analytics.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'analytics.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0f\x61nalytics.proto\x12\x0c\x61nalytics.v1\"\xb3\x01\n\x11RawClientResponse\x12\x13\n\x0bquestion_id\x18\x01 \x01(\t\x12\x31\n\rquestion_type\x18\x02 \x01(\x0e\x32\x1a.analytics.v1.QuestionType\x12\x15\n\rquestion_text\x18\x03 \x01(\t\x12\x17\n\x0fselected_weight\x18\x04 \x01(\x01\x12\x14\n\x0c\x63\x61tegory_tag\x18\x05 \x01(\t\x12\x10\n\x08raw_text\x18\x06 \x01(\t\"\xa9\x01\n\x15GenerateReportRequest\x12\x12\n\nsession_id\x18\x01 \x01(\t\x12*\n\x06\x66ormat\x18\x02 \x01(\x0e\x32\x1a.analytics.v1.ReportFormat\x12\x1c\n\x14\x63lient_metadata_json\x18\x03 \x01(\t\x12\x32\n\tresponses\x18\x04 \x03(\x0b\x32\x1f.analytics.v1.RawClientResponse\"`\n\x16GenerateReportResponse\x12\x14\n\x0c\x66ile_content\x18\x01 \x01(\x0c\x12\x14\n\x0c\x63ontent_type\x18\x02 \x01(\t\x12\x1a\n\x12suggested_filename\x18\x03 \x01(\t*C\n\x0cQuestionType\x12\x1d\n\x19QUESTION_TYPE_UNSPECIFIED\x10\x00\x12\n\n\x06\x43HOICE\x10\x01\x12\x08\n\x04TEXT\x10\x02*\x9b\x01\n\x0cReportFormat\x12\x1d\n\x19REPORT_FORMAT_UNSPECIFIED\x10\x00\x12\x16\n\x12REPORT_FORMAT_DOCX\x10\x01\x12\x16\n\x12REPORT_FORMAT_HTML\x10\x02\x12\x1d\n\x19REPORT_FORMAT_PSYCHO_DOCX\x10\x03\x12\x1d\n\x19REPORT_FORMAT_PSYCHO_HTML\x10\x04\x32o\n\x10\x41nalyticsService\x12[\n\x0eGenerateReport\x12#.analytics.v1.GenerateReportRequest\x1a$.analytics.v1.GenerateReportResponseBIZGsourcecraft.dev/benzo/bff/internal/clients/grpc/analyticspb;analyticspbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'analytics_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'ZGsourcecraft.dev/benzo/bff/internal/clients/grpc/analyticspb;analyticspb'
  _globals['_QUESTIONTYPE']._serialized_start=485
  _globals['_QUESTIONTYPE']._serialized_end=552
  _globals['_REPORTFORMAT']._serialized_start=555
  _globals['_REPORTFORMAT']._serialized_end=710
  _globals['_RAWCLIENTRESPONSE']._serialized_start=34
  _globals['_RAWCLIENTRESPONSE']._serialized_end=213
  _globals['_GENERATEREPORTREQUEST']._serialized_start=216
  _globals['_GENERATEREPORTREQUEST']._serialized_end=385
  _globals['_GENERATEREPORTRESPONSE']._serialized_start=387
  _globals['_GENERATEREPORTRESPONSE']._serialized_end=483
  _globals['_ANALYTICSSERVICE']._serialized_start=712
  _globals['_ANALYTICSSERVICE']._serialized_end=823
# @@protoc_insertion_point(module_scope)
